import { loadControls, latestPerControl } from './lib/load.mjs';

/**
 * Section 889 annual representation, REGENERATED from the live control rather than re-collected
 * as a standalone form each year.
 *
 * This is the Phase 4 payoff stated concretely. The conventional process is a form somebody signs
 * once a year on the strength of asking around. Here the representation is a projection of
 * ctl.scrm.procurement.telecom-equipment-attestation - the same population, the same query, the
 * same as-of date that everything else in the package is built from.
 *
 * THE REFUSAL THAT MATTERS
 *
 * The representation is a legal statement made to the Government, and False Claims Act exposure
 * attaches to the representation itself, not only to the equipment. So if the control has ANY
 * failing item, this refuses to draft an affirmative representation and says precisely which
 * population members block it.
 *
 * That includes items failing only as `manufacturer_unresolved`. "We could not determine the
 * manufacturer of three components" is not a basis for representing that no covered equipment is
 * used - it is a basis for representing nothing yet. Treating unresolved as clean is the exact
 * move that turns an incomplete inventory into a false certification.
 */

export const CONTROL_ID = 'ctl.scrm.procurement.telecom-equipment-attestation';

export function representation889({ assertions = [], controls = loadControls() } = {}) {
  const control = controls.find((c) => c.control_id === CONTROL_ID);
  const assertion = latestPerControl(assertions).find((a) => a.control_id === CONTROL_ID);

  if (!control) {
    return { state: 'no-control', blockers: [], body: null };
  }
  if (!assertion) {
    return {
      state: 'no-evidence',
      blockers: [],
      control,
      body: null,
    };
  }

  const blockers = assertion.failing ?? [];
  const state = blockers.length === 0 ? 'affirmative' : 'blocked';

  return {
    state,
    control,
    assertion,
    blockers,
    fixture: assertion.fixture === true,
    body: render({ state, control, assertion, blockers }),
  };
}

function render({ state, control, assertion, blockers }) {
  const out = [];
  out.push('# Section 889 representation — DRAFT, generated');
  out.push('');
  out.push(
    '<!-- GENERATED by `ccp representation 889` from ' +
      `${control.control_id}. Do not hand edit. This is a projection of a control, not a form: ` +
      'if it says the wrong thing, the control or its population is wrong. -->'
  );
  out.push('');
  out.push(`- **Control:** \`${control.control_id}\``);
  out.push(`- **Evidence as of:** ${assertion.as_of}`);
  out.push(`- **Population:** ${assertion.population_definition.trim()}`);
  out.push(`- **Query:** \`${assertion.query_ref}\` over ${assertion.source_system}`);
  out.push(`- **Result:** ${assertion.passing_count} of ${assertion.total} components resolved and clear`);
  out.push('');

  if (assertion.fixture) {
    out.push('> **NOT REAL EVIDENCE.** Generated from synthetic assertions. Must not be submitted.');
    out.push('');
  }

  if (state === 'affirmative') {
    out.push('## Draft representation');
    out.push('');
    out.push(
      'Based on the full population above — not a sample, and not an internal enquiry — no item ' +
        'resolves to a covered manufacturer or a named affiliate as a substantial or essential ' +
        'component of any system, or as critical technology.'
    );
    out.push('');
    out.push(
      '**This remains a draft for the responsible official to make.** The control establishes the ' +
        'factual basis; making the representation is a legal act and is a person’s to perform, ' +
        'not a generator’s.'
    );
  } else {
    out.push('## No affirmative representation can be drafted');
    out.push('');
    out.push(
      `${blockers.length} population member(s) block it. False Claims Act exposure attaches to the ` +
        'representation itself, so an unresolved item is a basis for representing **nothing yet** — ' +
        'never for representing that no covered equipment is used.'
    );
    out.push('');
    out.push('| Subject | Reason | First observed |');
    out.push('|---|---|---|');
    for (const b of blockers) {
      out.push(`| \`${b.subject_id}\` | ${b.reason} | ${b.first_observed} |`);
    }
    out.push('');
    out.push('Resolve every row above, re-run the control, and re-generate.');
  }

  out.push('');
  out.push('---');
  out.push('');
  out.push(
    'Regenerated from the operating control rather than re-collected annually. The population and ' +
      'the covered-equipment reference edition are the things to keep current; the representation ' +
      'follows from them.'
  );
  return `${out.join('\n')}\n`;
}

export function formatRepresentation(r) {
  switch (r.state) {
    case 'no-control':
      return `No ${CONTROL_ID} in the inventory - nothing to represent from.`;
    case 'no-evidence':
      return (
        `${CONTROL_ID} exists but has produced no assertion. A representation with no evidence ` +
        'behind it is the form-signing process this control replaces.'
      );
    case 'affirmative':
      return (
        'Section 889: draft affirmative representation generated.\n' +
        `  ${r.assertion.total} components, all resolved and clear as of ${r.assertion.as_of}.\n` +
        (r.fixture ? '  NOT REAL EVIDENCE - generated from fixtures, must not be submitted.\n' : '') +
        '  Making the representation is a legal act and remains a person’s to perform.'
      );
    default:
      return (
        'Section 889: REFUSING to draft an affirmative representation.\n' +
        `  ${r.blockers.length} of ${r.assertion.total} components block it as of ${r.assertion.as_of}:\n` +
        r.blockers.map((b) => `    ${b.subject_id}  ${b.reason}`).join('\n') +
        '\n  An unresolved manufacturer is a basis for representing nothing yet, never for ' +
        'representing that no covered equipment is used.'
      );
  }
}
